# Avoid production credentials in the repository,
# instead read the configuration from the environment.
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  host    : localhost
#  host: 172.16.27.211
  database: furnix_development
  # socket: /tmp/mysql.sock

development:
  <<: *default
  database: furnix_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
  
